# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'RottenTomatoes' do
    pod 'AFNetworking', '~> 2.5'
    pod 'SwiftyJSON', '~> 2.2'
    pod 'SVProgressHUD', '~> 1.1'
end

target 'RottenTomatoesTests' do

end

